---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker containers
        run: docker-compose build
      - name: Run Prettier
        run: docker-compose run --rm react npm run prettier -- --check
      - name: Run ESLint
        run: docker-compose run --rm react npm run eslint
      - name: Run Tests
        run: docker-compose run --rm react npm test